<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Exclusion list
    |--------------------------------------------------------------------------
    |
    | This is a list of exclusions for words or phrases where the original
    | form of the word has the same spelling in a given language.
    |
    */

    'Action',
    'Actions',
    'Afghanistan',
    'Angola',
    'Anguilla',
    'Aruba',
    'Bahamas',
    'Bangladesh',
    'Botswana',
    'Burkina Faso',
    'Burundi',
    'Canada',
    'Code',
    'Code',
    'Congo',
    'Costa Rica',
    'Cuba',
    'Curaçao',
    'Djibouti',
    'El Salvador',
    'Email',
    'France',
    'Gabon',
    'Ghana',
    'Gilbratar',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guatemala',
    'Guyana',
    'Honduras',
    'Hong Kong',
    'ID',
    'Jersey',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Lesotho',
    'Liechtenstein',
    'Luxembourg',
    'Macao',
    'Madagascar',
    'Malawi',
    'Maldives',
    'Mali',
    'Martinique',
    'Mayotte',
    'Monaco',
    'Montserrat',
    'Mozambique',
    'Myanmar',
    'Nauru',
    'Nicaragua',
    'Niger',
    'Oman',
    'Original',
    'Pakistan',
    'Panama',
    'Permissions',
    'Philippines',
    'Pitcairn',
    'Portugal',
    'Qatar',
    'Rwanda',
    'Samoa',
    'Seychelles',
    'Sri Lanka',
    'Suriname',
    'Taiwan',
    'Togo',
    'Tokelau',
    'Tonga',
    'total',
    'Tuvalu',
    'Ukraine',
    'Uruguay',
    'Vanuatu',
    'Zimbabwe',
];
