<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
| This list contains values.
|
*/

return [
    'Action Status',
    'Afghanistan',
    'Angola',
    'Anguilla',
    'API Token',
    'April',
    'Aruba',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Barbados',
    'Belize',
    'Benin',
    'Bermuda',
    'Bolivia',
    'Botswana',
    'Bouvet Island',
    'Burkina Faso',
    'Burundi',
    'Chad',
    'China',
    'Christmas Island',
    'Colombia',
    'Costa Rica',
    'Côte d\'Ivoire',
    'Ecuador',
    'Eritrea',
    'Finland',
    'Ghana',
    'Gibraltar',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'ID',
    'Iran, Islamic Republic Of',
    'Israel',
    'Jamaica',
    'Japan',
    'Jersey',
    'Kazakhstan',
    'Kiribati',
    'Kosovo',
    'Kyrgyzstan',
    'Lao People\'s Democratic Republic',
    'Lens',
    'Lesotho',
    'Liechtenstein',
    'Macao',
    'Malawi',
    'Maldives',
    'Malta',
    'Martinique',
    'Mauritius',
    'Mayotte',
    'Monaco',
    'Montenegro',
    'Montserrat',
    'Myanmar',
    'Nauru',
    'Nepal',
    'New Caledonia',
    'Nicaragua',
    'Niger',
    'Niue',
    'Norfolk Island',
    'November',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Paraguay',
    'Peru',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Rwanda',
    'Samoa',
    'San Marino',
    'Senegal',
    'September',
    'Sierra Leone',
    'Sint Maarten (Dutch part)',
    'Sri Lanka',
    'Suriname',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Togo',
    'Tokelau',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Update',
    'Update :resource',
    'Update :resource: :title',
    'Uruguay',
    'Vanuatu',
    'Venezuela',
    'Zimbabwe',
];
