<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
| This list contains values.
|
*/

return [
    ':resource Details',
    ':resource Details: :title',
    'Action Name',
    'Action Status',
    'Administrator',
    'Afghanistan',
    'Andorra',
    'Angola',
    'Anguilla',
    'April',
    'Aruba',
    'August',
    'Bahamas',
    'Bahrain',
    'Barbados',
    'Belarus',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Botswana',
    'Burkina Faso',
    'Burundi',
    'Chile',
    'China',
    'Code',
    'Costa Rica',
    'Curaçao',
    'Dashboard',
    'Details',
    'Dominica',
    'Ecuador',
    'Editor',
    'El Salvador',
    'Eritrea',
    'Gambia',
    'Ghana',
    'Gibraltar',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'ID',
    'Iran, Islamic Republic Of',
    'Isle Of Man',
    'Isle of Man',
    'Israel',
    'Japan',
    'Jersey',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Lao People\'s Democratic Republic',
    'Lens',
    'Lesotho',
    'Liberia',
    'Liechtenstein',
    'Macao',
    'Malawi',
    'Malaysia',
    'Mali',
    'Malta',
    'Martinique',
    'Mauritius',
    'Mayotte',
    'Monaco',
    'Montenegro',
    'Montserrat',
    'Myanmar',
    'Name',
    'Namibia',
    'Nauru',
    'Nepal',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'November',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Paraguay',
    'Peru',
    'Portugal',
    'Puerto Rico',
    'Reunion',
    'Réunion',
    'Saint Helena',
    'Saint Lucia',
    'Saint Martin',
    'Samoa',
    'San Marino',
    'Senegal',
    'September',
    'Sierra Leone',
    'Sint Maarten (Dutch part)',
    'Somalia',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Taiwan',
    'Thailand',
    'Togo',
    'Tokelau',
    'Tonga',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'Uruguay',
    'Vanuatu',
    'Venezuela',
];
