<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
*/

return [
    ':amount Total',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Benin',
    'Bermuda',
    'Bolivia',
    'Botswana',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Costa Rica',
    'Cuba',
    'Dominica',
    'Ecuador',
    'Editor',
    'El Salvador',
    'Eritrea',
    'Estonia',
    'Gambia',
    'Georgia',
    'Ghana',
    'Gibraltar',
    'Grenada',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guyana',
    'Honduras',
    'Hong Kong',
    'ID',
    'India',
    'Indonesia',
    'Iraq',
    'Israel',
    'Jamaica',
    'Jane Doe',
    'Jersey',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Lao People\'s Democratic Republic',
    'Lens',
    'Liberia',
    'Liechtenstein',
    'Macao',
    'Madagascar',
    'Malta',
    'Mauritania',
    'Mayotte',
    'Micronesia, Federated States Of',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Nicaragua',
    'Nigeria',
    'Niue',
    'No',
    'Oh no',
    'Original',
    'Palau',
    'Paraguay',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Samoa',
    'San Marino',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Somalia',
    'Sri Lanka',
    'Suriname',
    'Swaziland',
    'Tanzania',
    'Togo',
    'Tokelau',
    'Tonga',
    'total',
    'Total:',
    'Tunisia',
    'Tuvalu',
    'Uganda',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Viet Nam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
];
