<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
*/

return [
    'Andorra',
    'Angola',
    'Anguilla',
    'Argentina',
    'Aruba',
    'August',
    'Austria',
    'Bangladesh',
    'Barbados',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Botswana',
    'Burkina Faso',
    'Burundi',
    'Colombia',
    'Costa Rica',
    'Djibouti',
    'Ecuador',
    'Eritrea',
    'Gabon',
    'Gambia',
    'Ghana',
    'Gibraltar',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Haiti',
    'Honduras',
    'ID',
    'India',
    'Jamaica',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Lao People\'s Democratic Republic',
    'Lesotho',
    'Liechtenstein',
    'Malawi',
    'Malta',
    'Martinique',
    'Mauritius',
    'Mayotte',
    'Moldova',
    'Monaco',
    'Montenegro',
    'Montserrat',
    'Myanmar',
    'Nauru',
    'Nepal',
    'Nicaragua',
    'Niger',
    'Niue',
    'November',
    'Pakistan',
    'Palau',
    'Panama',
    'Paraguay',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Rwanda',
    'Saint Helena',
    'Saint Lucia',
    'Saint Martin',
    'Samoa',
    'San Marino',
    'Senegal',
    'September',
    'Serbia',
    'Sierra Leone',
    'Sint Maarten (Dutch part)',
    'Sri Lanka',
    'Suriname',
    'Taiwan',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tuvalu',
    'Uganda',
    'Uruguay',
    'Vanuatu',
    'Venezuela',
    'Zimbabwe',
];
