<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
*/

return [
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Anguilla',
    'Armenia',
    'Aruba',
    'Australia',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Botswana',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Chile',
    'Costa Rica',
    'Curaçao',
    'Djibouti',
    'Dominica',
    'Ecuador',
    'El Salvador',
    'Eritrea',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Gibraltar',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea-Bissau',
    'Guinea',
    'Guyana',
    'Haiti',
    'Honduras',
    'Indonesia',
    'Israel',
    'Jamaica',
    'Jersey',
    'Jordan',
    'Kiribati',
    'Korea',
    'Kosovo',
    'Kuwait',
    'Latvia',
    'Lens',
    'Lesotho',
    'Liberia',
    'Libyan Arab Jamahiriya',
    'Liechtenstein',
    'Macao',
    'Malawi',
    'Mali',
    'Malta',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Paraguay',
    'Peru',
    'Puerto Rico',
    'Qatar',
    'Réunion',
    'Romania',
    'Saint Helena',
    'Saint Lucia',
    'Samoa',
    'San Marino',
    'Senegal',
    'Serbia',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Somalia',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Taiwan',
    'Togo',
    'Tokelau',
    'Tunisia',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Zimbabwe',
];
