<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
*/

return [
    'Albania',
    'Algeria',
    'Angola',
    'Anguilla',
    'Armenia',
    'Aruba',
    'Australia',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Botswana',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Chad',
    'Chile',
    'Costa Rica',
    'Djibouti',
    'Ecuador',
    'Eritrea',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Gibraltar',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Indonesia',
    'Iran, Islamic Republic Of',
    'Israel',
    'Jamaica',
    'Jersey',
    'Jordan',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Lao People\'s Democratic Republic',
    'Latvia',
    'Lesotho',
    'Liberia',
    'Libyan Arab Jamahiriya',
    'Liechtenstein',
    'Macao',
    'Malawi',
    'Malta',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Paraguay',
    'Peru',
    'Puerto Rico',
    'Qatar',
    'Romania',
    'Saint Barthelemy',
    'Saint Martin',
    'Samoa',
    'San Marino',
    'Senegal',
    'Serbia',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten (Dutch part)',
    'Slovakia',
    'Slovenia',
    'Somalia',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Taiwan',
    'Togo',
    'Tokelau',
    'Tunisia',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Zimbabwe',
];
