<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
*/

return [
    ':amount Total',
    'Action',
    'Actions',
    'Afghanistan',
    'Aland Islands',
    'Angola',
    'Anguilla',
    'Aruba',
    'Bahamas',
    'Bangladesh',
    'Botswana',
    'Burkina Faso',
    'Burundi',
    'Canada',
    'Code',
    'Congo',
    'Costa Rica',
    'Coupon',
    'Côte d\'Ivoire',
    'Cuba',
    'Curaçao',
    'Djibouti',
    'El Salvador',
    'Email',
    'France',
    'Gabon',
    'Ghana',
    'Gibraltar',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guyana',
    'Honduras',
    'Hong Kong',
    'ID',
    'Iran, Islamic Republic Of',
    'Jersey',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Lao People\'s Democratic Republic',
    'Lesotho',
    'Liechtenstein',
    'Luxembourg',
    'Macao',
    'Madagascar',
    'Malawi',
    'Maldives',
    'Mali',
    'Martinique',
    'Mayotte',
    'Monaco',
    'Montserrat',
    'Mozambique',
    'Myanmar',
    'Nauru',
    'Nicaragua',
    'Niger',
    'Niue',
    'Oman',
    'Original',
    'Pakistan',
    'Panama',
    'Paraguay',
    'Permissions',
    'Philippines',
    'Pitcairn',
    'Portugal',
    'Qatar',
    'Reunion',
    'Rwanda',
    'Samoa',
    'Seychelles',
    'Sint Maarten (Dutch part)',
    'Sri Lanka',
    'Suriname',
    'Taiwan',
    'Togo',
    'Tokelau',
    'Tonga',
    'total',
    'Total:',
    'Tuvalu',
    'Ukraine',
    'Uruguay',
    'Vanuatu',
    'Zimbabwe',
];
