<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
*/

return [
    'Administrator',
    'Albania',
    'Andorra',
    'Angola',
    'Anguilla',
    'April',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Botswana',
    'Brazil',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Chad',
    'Curaçao',
    'Denmark',
    'Djibouti',
    'Edit',
    'Edit :resource',
    'Editor',
    'El Salvador',
    'Eritrea',
    'Estonia',
    'Fiji',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Gibraltar',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'ID',
    'India',
    'Indonesia',
    'Iraq',
    'Iran, Islamic Republic Of',
    'Israel',
    'Jersey',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    "Lao People's Democratic Republic",
    'Latvia',
    'Lebanon',
    'Lens',
    'Lesotho',
    'Liberia',
    'Libyan Arab Jamahiriya',
    'Liechtenstein',
    'Malawi',
    'Malaysia',
    'Mali',
    'Malta',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Moldova',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Niger',
    'Nigeria',
    'Niue',
    'November',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Paraguay',
    'Peru',
    'Portugal',
    'Qatar',
    'Romania',
    'Rwanda',
    'Saint Barthelemy',
    'Saint Helena',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Martin',
    'Saint Pierre and Miquelon',
    'Saint Vincent and Grenadines',
    'Samoa',
    'San MarinoID',
    'Senegal',
    'September',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Sint Maarten(Dutch part)',
    'Slovenia',
    'Somalia',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor - Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'total',
    'Tunisia',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Zambia',
    'Zimbabwe',
];
