<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
*/

return [
    'Administrator',
    'Albania',
    'Andorra',
    'Angola',
    'Anguilla',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahrain',
    'Bangladesh',
    'Belarus',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Botswana',
    'Brazil',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Chad',
    'Curaçao',
    'Denmark',
    'Djibouti',
    'Edit',
    'El Salvador',
    'Eritrea',
    'Estonia',
    'Fiji',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Gibraltar',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'India',
    'Indonesia',
    'Iraq',
    'Israel',
    'Jersey',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Latvia',
    'Lebanon',
    'Lens',
    'Lesotho',
    'Liberia',
    'Liechtenstein',
    'Malawi',
    'Malaysia',
    'Mali',
    'Malta',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Moldova',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Niger',
    'Nigeria',
    'Niue',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Paraguay',
    'Peru',
    'Portugal',
    'Qatar',
    'Romania',
    'Rwanda',
    'Saint Barthelemy',
    'Saint Helena',
    'Saint Kitts And Nevis',
    'Saint Lucia',
    'Saint Martin',
    'Saint Pierre And Miquelon',
    'Saint Vincent And Grenadines',
    'Samoa',
    'San Marino',
    'Senegal',
    'September',
    'Seychelles',
    'Sierra Leone',
    'Sint Maarten',
    'Slovenia',
    'Somalia',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'total',
    'Tunisia',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Zambia',
    'Zimbabwe'
];
