<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Exclusion list
    |--------------------------------------------------------------------------
    |
    | This is a list of exclusions for words or phrases where the original
    | form of the word has the same spelling in a given language.
    |
    */

    'ID',
    'Email',
    'Oh no',
    'Editor',
    'Password',
    'Dashboard',
    'No',

    /**
     * Countries
     */
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Anguilla',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Bahamas',
    'Bangladesh',
    'Barbados',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Botswana',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Canada',
    'Chad',
    'Colombia',
    'Congo',
    'Costa Rica',
    'Cuba',
    'Dominica',
    'Ecuador',
    'El Salvador',
    'Eritrea',
    'Estonia',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'India',
    'Indonesia',
    'Iran, Islamic Republic Of',
    'Iraq',
    'Jersey',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Lao People\'s Democratic Republic',
    'Lesotho',
    'Liberia',
    'Liechtenstein',
    'Macao',
    'Madagascar',
    'Malawi',
    'Mali',
    'Malta',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Micronesia, Federated States Of',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Paraguay',
    'Qatar',
    'Romania',
    'Samoa',
    'San Marino',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten (Dutch part)',
    'Slovenia',
    'Somalia',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Taiwan',
    'Tanzania',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'Tunisia',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
];
