<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
*/

return [
    'Action Status',
    'Administrator',
    'Afghanistan',
    'Albania',
    'Andorra',
    'Angola',
    'Anguilla',
    'April',
    'Argentina',
    'Armenia',
    'Aruba',
    'August',
    'Australia',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Botswana',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Chile',
    'Colombia',
    'Costa Rica',
    'Cuba',
    'Curaçao',
    'Dashboard',
    'Djibouti',
    'Dominica',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Eritrea',
    'Fiji',
    'Finland',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Gibraltar',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'ID',
    'India',
    'Indonesia',
    'Iran, Islamic Republic Of',
    'Isle of Man',
    'Isle Of Man',
    'Israel',
    'Jamaica',
    'Japan',
    'Jersey',
    'Jordan',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Latvia',
    'Lesotho',
    'Liberia',
    'Libyan Arab Jamahiriya',
    'Liechtenstein',
    'Macao',
    'Malawi',
    'Malaysia',
    'Mali',
    'Malta',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'November',
    'Oman',
    'Original',
    'Pakistan',
    'Palau',
    'Panama',
    'Paraguay',
    'Peru',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Reunion',
    'Romania',
    'Rwanda',
    'Réunion',
    'Samoa',
    'San Marino',
    'Senegal',
    'September',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten (Dutch part)',
    'Slovakia',
    'Slovenia',
    'Somalia',
    'Sri Lanka',
    'Sudan',
    'Syrian Arab Republic',
    'Taiwan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tokelau',
    'Tonga',
    'total',
    'Total:',
    'Tunisia',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Uruguay',
    'Vanuatu',
    'Venezuela',
    'Zambia',
    'Zimbabwe',
];
