<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
*/

return [
    'Action Status',
    'Afghanistan',
    'Angola',
    'Anguilla',
    'Antarctica',
    'April',
    'Armenia',
    'Aruba',
    'Bangladesh',
    'Belarus',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Botswana',
    'Bouvet Island',
    'Burkina Faso',
    'Canada',
    'China',
    'Code',
    'Colombia',
    'Congo',
    'Constant',
    'Costa Rica',
    'Cuba',
    'Curaçao',
    'Cyprus',
    'Dashboard',
    'December',
    'Ecuador',
    'Email',
    'Eritrea',
    'Fiji',
    'Finland',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Gibraltar',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'ID',
    'India',
    'Iran, Islamic Republic Of',
    'Japan',
    'Jersey',
    'Kiribati',
    'Kosovo',
    'Lao People\'s Democratic Republic',
    'Lens',
    'Lesotho',
    'Liberia',
    'Liechtenstein',
    'Madagascar',
    'Malawi',
    'Malta',
    'Martinique',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Monaco',
    'Montenegro',
    'Montserrat',
    'Mozambique',
    'Myanmar',
    'Nauru',
    'Nepal',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'November',
    'Oman',
    'Palau',
    'Panama',
    'Paraguay',
    'Peru',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Saint Barthelemy',
    'Saint Martin',
    'Samoa',
    'San Marino',
    'Senegal',
    'September',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten (Dutch part)',
    'Sri Lanka',
    'Start Polling',
    'Stop Polling',
    'Suriname',
    'Taiwan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tokelau',
    'Tonga',
    'Turkmenistan',
    'Tuvalu',
    'Vanuatu',
    'Venezuela',
    'Zambia',
    'Zimbabwe',
];
