<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
*/

return [
    'Administrator',
    'Albania',
    'Angola',
    'Anguilla',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Barbados',
    'Belize',
    'Benin',
    'Bhutan',
    'Botswana',
    'Bouvet Island',
    'Burkina Faso',
    'Burundi',
    'Chile',
    'Curaçao',
    'Email',
    'Estonia',
    'Gabon',
    'Gambia',
    'Ghana',
    'Gibraltar',
    'Grenada',
    'Guam',
    'Guernsey',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'Lesotho',
    'Liberia',
    'Liechtenstein',
    'Luxembourg',
    'Malawi',
    'Mali',
    'Malta',
    'Mauritius',
    'Mongolia',
    'Montserrat',
    'Namibia',
    'Nauru',
    'Nepal',
    'Niger',
    'Nigeria',
    'Niue',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Peru',
    'Réunion',
    'Rwanda',
    'Samoa',
    'San Marino',
    'Senegal',
    'Serbia',
    'Sierra Leone',
    'Somalia',
    'Togo',
    'Tokelau',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Uzbekistan',
    'Vanuatu',
    'Zambia',
    'Zimbabwe',
];
