<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
| This list contains values.
|
*/

return [
    'Andorra',
    'Angola',
    'Argentina',
    'Aruba',
    'Bahamas',
    'Bangladesh',
    'Barbados',
    'Belize',
    'Bermuda',
    'Burundi',
    'Chile',
    'China',
    'Congo',
    'Costa Rica',
    'Cuba',
    'Curaçao',
    'Dominica',
    'Editor',
    'El Salvador',
    'Fiji',
    'Gambia',
    'Georgia',
    'Gibraltar',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'ID',
    'Israel',
    'Jamaica',
    'Jersey',
    'Kosovo',
    'Kuwait',
    'Lens',
    'Liechtenstein',
    'Madagascar',
    'Malawi',
    'Mali',
    'Malta',
    'Mauritania',
    'Mayotte',
    'Mexico',
    'Monaco',
    'Montenegro',
    'Myanmar',
    'Nauru',
    'Nepal',
    'Niue',
    'Original',
    'Palau',
    'Panama',
    'Peru',
    'Portugal',
    'Qatar',
    'Samoa',
    'Senegal',
    'Sri Lanka',
    'Suriname',
    'Taiwan',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'total',
    'Total:',
    'Tuvalu',
    'Uganda',
    'Vanuatu',
    'Venezuela',
];
