<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
*/

return [
    'Andorra',
    'Angola',
    'Argentina',
    'Aruba',
    'Bahamas',
    'Bangladesh',
    'Barbados',
    'Belize',
    'Bermuda',
    'Burundi',
    'Canada',
    'Chile',
    'China',
    'Congo',
    'Costa Rica',
    'Cuba',
    'Curaçao',
    'Dominica',
    'Editor',
    'El Salvador',
    'Fiji',
    'Gambia',
    'Georgia',
    'Gibraltar',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'ID',
    'India',
    'Indonesia',
    'Israel',
    'Jamaica',
    'Jersey',
    'Kosovo',
    'Kuwait',
    'Lao People\'s Democratic Republic',
    'Lens',
    'Liechtenstein',
    'Madagascar',
    'Malawi',
    'Mali',
    'Malta',
    'Mauritania',
    'Mayotte',
    'Mexico',
    'Monaco',
    'Montenegro',
    'Myanmar',
    'Nauru',
    'Nepal',
    'Nigeria',
    'Niue',
    'Original',
    'Palau',
    'Panama',
    'Peru',
    'Portugal',
    'Qatar',
    'Saint Barthelemy',
    'Samoa',
    'Sao Tome And Principe',
    'Senegal',
    'Sint Maarten (Dutch part)',
    'Sri Lanka',
    'Suriname',
    'Taiwan',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'total',
    'Tuvalu',
    'Uganda',
    'Vanuatu',
    'Venezuela',
];
