<?php

/*
|--------------------------------------------------------------------------
| Exclusion list
|--------------------------------------------------------------------------
|
| This is a list of exclusions for words or phrases where the original
| form of the word has the same spelling in a given language.
|
*/

return [
    'Andorra',
    'Angola',
    'Anguilla',
    'Aruba',
    'Barbados',
    'Belize',
    'Benin',
    'Bermuda',
    'Burkina Faso',
    'Burundi',
    'Cape Verde',
    'Curaçao',
    'Fiji',
    'Grenada',
    'Guadeloupe',
    'Guatemala',
    'Guernsey',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'Jane Doe',
    'Jersey',
    'Kenya',
    'Lens',
    'Lesotho',
    'Libyan Arab Jamahiriya',
    'Macao',
    'Malta',
    'Mauritius',
    'Mayotte',
    'Moldova',
    'Montserrat',
    'Myanmar',
    'Nauru',
    'Nepal',
    'Niue',
    'Pakistan',
    'Palau',
    'Panama',
    'Paraguay',
    'Peru',
    'Réunion',
    'Saint Lucia',
    'Saint Martin',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Senegal',
    'Sierra Leone',
    'Sint Maarten (Dutch part)',
    'Sri Lanka',
    'Sudan',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'Tuvalu',
    'Uganda',
    'Uruguay',
    'Vanuatu',
    'Venezuela',
    'Yemen',
];
