name: Machine Translation

on:
    schedule:
        -   cron: 17 1 1,15 * *
    workflow_dispatch:

permissions: write-all

jobs:
    translate:
        uses: Laravel-Lang/.github/.github/workflows/translate.yml@main
